// Respaldo de los productos de ejemplo originales.
// Si algún día quieres volver a tener estos 16 artículos:
//   - Pon esta lista como el contenido de `var PRODUCTS = [ ... ];` en data.js
// Este archivo no afecta a la app.
var DEMO_PRODUCTS = [
  { id: "p01", title: "Nike Dunk Low \"Panda\"", brand: "Nike", cat: "shoes", supplierId: "hipobuy", rating: 4.9, reviews: 4120, price: 34.90, orig: 54.90, grams: 980, mono: "ND", grad: ["#cbd5e1", "#64748b"], deal: "none", complaints: 0, fit: "shoe", note: "Comfy, talle normal. Fotos QC disponibles." },
  { id: "p02", title: "Air Jordan 4 \"Bred\"", brand: "Jordan/Nike", cat: "shoes", supplierId: "kakobuy", rating: 4.9, reviews: 1860, price: 49.90, orig: 79.90, grams: 1200, mono: "AJ4", grad: ["#ef4444", "#7f1d1d"], deal: "flash", complaints: 0, fit: "shoe", flash: { total: 3, minutes: 5 }, note: "CVW factory. Talle normal." },
  { id: "p03", title: "Yeezy Boost 350 V2 \"Core Black\"", brand: "Adidas", cat: "shoes", supplierId: "acbuy", rating: 4.8, reviews: 2210, price: 39.90, orig: 65.90, grams: 1050, mono: "YB", grad: ["#f1f5f9", "#94a3b8"], deal: "none", complaints: 0, fit: "shoe", note: "Boost auténtico al tacto. Talle medio: pide 0.5 arriba." },
  { id: "p04", title: "Champion Reverse Weave Hoodie", brand: "Champion", cat: "top", supplierId: "superbuy", rating: 4.9, reviews: 3350, price: 41.90, orig: 69.90, grams: 850, mono: "CR", grad: ["#1e3a5f", "#0f172a"], deal: "none", complaints: 0, fit: "top", note: "Algodón grueso, costuras dobles." },
  { id: "p05", title: "FOG Essentials Tee (caja perfecta)", brand: "Essentials", cat: "top", supplierId: "sugargoo", rating: 4.8, reviews: 2980, price: 24.90, orig: 39.90, grams: 260, mono: "FT", grad: ["#f8fafc", "#475569"], deal: "earlybird", complaints: 0, fit: "top", early: { quota: 25 }, note: "Talle oversized real, va grande." },
  { id: "p06", title: "Nike Tech Fleece Pants", brand: "Nike", cat: "bottom", supplierId: "oopbuy", rating: 4.9, reviews: 1740, price: 35.90, orig: 59.90, grams: 640, mono: "NT", grad: ["#334155", "#0f172a"], deal: "none", complaints: 0, fit: "bottom", note: "Talle según cintura, táper regular." },
  { id: "p07", title: "Arc'teryx Alpha Jacket (GTX)", brand: "Arc'teryx", cat: "outer", supplierId: "hipobuy", rating: 4.9, reviews: 960, price: 89.90, orig: 149.90, grams: 780, mono: "AX", grad: ["#065f46", "#022c22"], deal: "pricedrop", complaints: 0, fit: "top", drop: { floor: 69.90, step: 1.50, everyMin: 2 }, note: "Membrana real, sellado con cinta." },
  { id: "p08", title: "Rolex Datejust 41 (VSF)", brand: "Rolex", cat: "acc", supplierId: "cnfans", rating: 4.8, reviews: 640, price: 145.90, orig: 210.90, grams: 320, mono: "DJ", grad: ["#a16207", "#422006"], deal: "auction", complaints: 0, fit: "none", auc: { start: 129.00, minInc: 4.00, mins: 15 }, note: "VSF, calibre 3235. Caja 41 mm." },
  { id: "p09", title: "LV Monogram Belt 110cm", brand: "Louis Vuitton", cat: "acc", supplierId: "cssbuy", rating: 4.8, reviews: 1520, price: 38.90, orig: 59.90, grams: 410, mono: "LV", grad: ["#92400e", "#451a03"], deal: "fastpay", complaints: 0, fit: "none", fast: { mins: 10, discStart: 6 }, note: "Hebilla metálica grabada." },
  { id: "p10", title: "Air Force 1 Low \"Triple White\"", brand: "Nike", cat: "shoes", supplierId: "acbuy", rating: 4.9, reviews: 3610, price: 33.90, orig: 52.90, grams: 1000, mono: "AF1", grad: ["#ffffff", "#cbd5e1"], deal: "watch", complaints: 0, fit: "shoe", note: "Clásico que no falla. Talle normal." },
  { id: "p11", title: "Balenciaga Speed Trainer", brand: "Balenciaga", cat: "shoes", supplierId: "kakobuy", rating: 4.8, reviews: 890, price: 48.90, orig: 74.90, grams: 880, mono: "BS", grad: ["#0f172a", "#334155"], deal: "none", complaints: 0, fit: "shoe", note: "Knit elástico, pide la talla de siempre." },
  { id: "p12", title: "Stussy Worldwide Hoodie", brand: "Stussy", cat: "top", supplierId: "superbuy", rating: 4.9, reviews: 2050, price: 37.90, orig: 59.90, grams: 620, mono: "ST", grad: ["#b91c1c", "#450a0a"], deal: "none", complaints: 0, fit: "top", note: "Print sólido, algodón pesado." },
  { id: "p13", title: "Diesel Straight Jeans (raw selvedge)", brand: "Diesel", cat: "bottom", supplierId: "sugargoo", rating: 4.8, reviews: 1270, price: 44.90, orig: 69.90, grams: 780, mono: "DN", grad: ["#1d4ed8", "#172554"], deal: "none", complaints: 0, fit: "bottom", note: "Selvage real. Mide la cintura en cm, no la letra." },
  { id: "p14", title: "Adidas Ultraboost 1.0 (basf)", brand: "Adidas", cat: "shoes", supplierId: "cnfans", rating: 4.9, reviews: 1580, price: 43.90, orig: 67.90, grams: 960, mono: "UB", grad: ["#16a34a", "#052e16"], deal: "flash", complaints: 0, fit: "shoe", flash: { total: 3, minutes: 3 }, note: "Boost real (BASF). Va entera." },
  { id: "p15", title: "Carhartt WIP Beanie New York", brand: "Carhartt", cat: "acc", supplierId: "oopbuy", rating: 4.9, reviews: 980, price: 15.90, orig: 25.90, grams: 130, mono: "CB", grad: ["#7f1d1d", "#450a0a"], deal: "none", complaints: 0, fit: "none", note: "Punto acrílico doble." },
  { id: "p16", title: "Gucci Aviator Sunglasses GG0061S", brand: "Gucci", cat: "acc", supplierId: "cssbuy", rating: 4.8, reviews: 720, price: 32.90, orig: 49.90, grams: 210, mono: "GG", grad: ["#1e293b", "#0f172a"], deal: "pricedrop", complaints: 2, fit: "none", drop: { floor: 24.90, step: 1.00, everyMin: 3 }, note: "Lentes UV400 con grabado." },
];